### PR TITLE
IRON-23 Fixed routes and added support for snake case URL parameters (fixes #104)

### LINKED ISSUE #104: Fix routes (opinionated)
Fix the routes (which should in turn aid with reverse proxy setup).

### PR DESCRIPTION
**Pull request by cameronfletcher**
The PR changes the routes for Ironclad to match a more opionated set that can be configured on a reverse proxy.
In addition, this adds support for snake case URL parameters to match the snake case JSON content.

### CODE REVIEW

File: src/Ironclad/Controllers/ManageController.cs [hunk 1]
```diff
@@ -191,6 +196,7 @@ public async Task<IActionResult> ChangePassword(ChangePasswordModel model)
             return this.RedirectToAction(nameof(this.ChangePassword));
         }
 
+        [Route("/settings/setpassword")]
```
Comment (tarurar) [inline src/Ironclad/Controllers/ManageController.cs]: What's the difference between `/settings/changepassword` and `/settings/setpassword` from the API consumer point of view?

File: src/Ironclad/Extensions/SnakeCaseStringExtensions.cs [hunk 2]
```diff
@@ -0,0 +1,75 @@
+﻿// Copyright (c) Lykke Corp.
+// See the LICENSE file in the project root for more information.
+
+namespace Ironclad.Extensions
+{
+    using System.Text;
+
+    internal static class SnakeCaseStringExtensions
```
Comment (tarurar) [inline src/Ironclad/Extensions/SnakeCaseStringExtensions.cs]: Unit tests missed?

File: src/Ironclad/Controllers/ManageController.cs (hunk 1 above)
Comment (cameronfletcher) [reply src/Ironclad/Controllers/ManageController.cs]: `changepassword` allows you to change a password that already exists eg. for a local login
`setpassword` allows you to set a local password for an external login
